production:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 162.243.163.168
  db_server: localhost
  user: "deploy"
  server_name: 162.243.163.168
  full_app_name: "consul"

demo:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 165.227.72.56
  db_server: localhost
  user: "deploy"
  server_name: 165.227.72.56
  full_app_name: "consul"

lopc:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 159.89.40.239
  db_server: localhost
  user: "deploy"
  server_name: 159.89.40.239
  full_app_name: "consul"

sandbox:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 68.183.58.27
  db_server: localhost
  user: "deploy"
  server_name: 68.183.58.27
  full_app_name: "consul"

test:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 165.227.222.79
  db_server: localhost
  user: "deploy"
  server_name: 165.227.222.79
  full_app_name: "consul"

pb2:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 165.227.222.89
  db_server: localhost
  user: "deploy"
  server_name: 165.227.222.89
  full_app_name: "consul"

merced:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 165.227.222.63
  db_server: localhost
  user: "deploy"
  server_name: 165.227.222.89
  full_app_name: "consul"

strapis:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 142.93.66.252
  db_server: localhost
  user: "deploy"
  server_name: 142.93.66.252
  full_app_name: "consul"

mygov:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 68.183.123.247
  db_server: localhost
  user: "deploy"
  server_name: 68.183.123.247
  full_app_name: "consul"

nycliberations:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 68.183.123.231
  db_server: localhost
  user: "deploy"
  server_name: 68.183.123.231
  full_app_name: "consul"