production:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 162.243.163.168
  db_server: localhost
  user: "deploy"
  server_name: 162.243.163.168
  full_app_name: "consul"

demo:
  deploy_to: "/home/deploy/consul"
  ssh_port: 22
  server1: 165.227.72.56
  db_server: localhost
  user: "deploy"
  server_name: 165.227.72.56
  full_app_name: "consul"