default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""
  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  http_basic_username: "dev"
  http_basic_password: "pass"
  <<: *default
  <<: *maps

test:
  <<: *default
  <<: *maps

staging:
  secret_key_base: ""
  server_name: ""
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  <<: *default
  <<: *maps
  <<: *apis

preproduction:
  secret_key_base: ""
  server_name: ""
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""
  <<: *maps
  <<: *apis

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  server_name: <%= ENV['server_name'] %>
  rollbar_server_token: <%= ENV['rollbar_server_token'] %>
  http_basic_username: <%= ENV['http_basic_username'] %>
  http_basic_password: <%= ENV['http_basic_password'] %>
  managers_url: <%= ENV['managers_url'] %>
  managers_application_key: <%= ENV['managers_application_key'] %>
  twitter_key: <%= ENV['twitter_key'] %>
  twitter_secret: <%= ENV['twitter_secret'] %>
  facebook_key: <%= ENV['facebook_key'] %>
  facebook_secret: <%= ENV['facebook_secret'] %>
  google_oauth2_key: <%= ENV['google_oauth2_key'] %>
  google_oauth2_secret: <%= ENV['google_oauth2_secret'] %>
  <<: *maps
  <<: *apis
